fixes, WIP

diff --git a/rpi-bootstrap b/rpi-bootstrap
--- a/rpi-bootstrap
+++ b/rpi-bootstrap
@@ -23,6 +23,7 @@ rpi_release="2019-04-08-raspbian-stretch-lite"
 image="${rpi_release}.img"
 archive="${rpi_release}.zip"
 
+# TODO: download/unzip should be separate stages.
 if ! [ -f "${image}" ]; then
     echo "No raspbian image found, fetching..."
     if ! [ -f "${archive}" ]; then
@@ -44,7 +45,12 @@ fi
 
 # TODO: use guestfish which doesn't require sudo or loop devices
 sudo losetup -f ${image}
+# TODO: currently this sources all loop devices set up with this $image. Should identify images uniquely so only performing on one.
 loopdevice="$(sudo losetup -l | grep ${image} | awk -F ' ' '{print $1}')"
+# Just try partx; if it fails assume a previous partition was already successful.
+# TODO: find a way to do this in partx idempotently.
+sudo partx -a ${loopdevice} || true
+# TODO: see if rootfs can be set by info from partx.
 rootfs="/dev/$(lsblk -lf ${loopdevice} | grep rootfs | awk -F ' ' '{print $1}')"
 
 tmpdir="/tmp/${image}.d"
@@ -54,7 +60,8 @@ sudo mount ${rootfs} ${tmpdir}
 sudo ln -s /lib/systemd/system/ssh.service ${tmpdir}/etc/systemd/system/sshd.service
 sudo ln -s /lib/systemd/system/ssh.service ${tmpdir}/etc/systemd/system/multi-user.target.wants/ssh.service
 # Wireless config
-cat wpa_supplicant.conf <<EOF
+# TODO: write this to a tmp directory
+cat <<EOF > $(pwd)/wpa_supplicant.conf
 ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
 update_config=1
 country=${wpa_country}
@@ -63,26 +70,26 @@ network={
     psk=${wpa_psk}
 }
 EOF
-sudo cp wpa_supplicant.conf ${tmpdir}/etc/wpa_supplicant/wpa_supplicant.conf
+sudo cp $(pwd)/wpa_supplicant.conf ${tmpdir}/etc/wpa_supplicant/wpa_supplicant.conf
 # Checkin client
-cat rpi-provision-checkin.service <<EOF
-[Unit]
-Description=Check in to a rpi-provision server to request provisioning. Once provisioning is complete, this unit should be stopped and disabled by the server.
-Before=systemd-user-sessions.service
-Wants=network-online.target
-After=network-online.target
+# cat <<EOF > $(pwd)/rpi-provision-checkin.service
+# [Unit]
+# Description=Check in to a rpi-provision server to request provisioning. Once provisioning is complete, this unit should be stopped and disabled by the server.
+# Before=systemd-user-sessions.service
+# Wants=network-online.target
+# After=network-online.target
 
-[Service]
-Restart=always
-RestartSec=2
-RemainAfterExit=yes
-ExecStart=/usr/bin/curl --request POST --header "Content-Type: application/json" --data "{ \"ssh_port\": 22, \"ssh_user\": \"pi\" }" --url http://${provisioner_url}:${provisioner_port}/v0/checkin/
+# [Service]
+# Restart=always
+# RestartSec=2
+# RemainAfterExit=yes
+# ExecStart=/usr/bin/curl --request POST --header "Content-Type: application/json" --data "{ \"ssh_port\": 22, \"ssh_user\": \"pi\" }" --url http://${provisioner_url}:${provisioner_port}/v0/checkin/
 
-[Install]
-WantedBy=multi-user.target
-EOF
-sudo cp $(pwd)/rpi-provision-checkin.service ${tmpdir}/lib/systemd/system/rpi-provision-checkin.service
-sudo ln -s /lib/systemd/system/rpi-provision-checkin.service ${tmpdir}/etc/systemd/system/multi-user.target.wants/rpi-provision-checkin.service
+# [Install]
+# WantedBy=multi-user.target
+# EOF
+# sudo cp $(pwd)/rpi-provision-checkin.service ${tmpdir}/lib/systemd/system/rpi-provision-checkin.service
+# sudo ln -s /lib/systemd/system/rpi-provision-checkin.service ${tmpdir}/etc/systemd/system/multi-user.target.wants/rpi-provision-checkin.service
 # Provisioner pubkey
 # sudo mkdir -p ${tmpdir}/home/pi/.ssh
 # echo ${provisioner_pubkey} >> ${tmpdir}/home/pi/.ssh/authorized_keys
@@ -93,3 +100,5 @@ sudo losetup -d ${loopdevice}
 
 # TODO: split this into a separate stage
 sudo dd if=${image} of=${sd_card} bs=4M oflag=dsync status=progress
+sync
+mv -f ${image} ${image}.old
